config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments
  resources :posts
  get 'recipes/index'

  get 'nutrition_news/index'

  get 'news/index'

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :workoutposts
  root 'main#index'

  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }


  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete '/logout',
    to: 'sessions#destroy'

  get 'users/:id' => 'users#show', :as => 'user_profile'

  get 'about' => 'main#about'
  get 'contact' => 'main#contact'


  get 'workouts/new' => 'workouts#new'
  get 'workouts' => 'workouts#index'
  get 'workouts/show/:workouts_id' => 'workouts#show', :as => 'show_workout'

  get 'new' => 'news#index'

  get 'video' => 'video#index'

  get 'chest' => 'main#chest'
  get 'arms' => 'main#arms'
  get 'back' => 'main#back'
  get 'cardio' => 'main#cardio'
  get 'legs' => 'main#legs'


  get '/auth/:provider/callback', to: 'sessions#oauth'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
end

app/controllers/admin/workouts_controller.rb
module Admin
  class WorkoutsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Workout.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Workout.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

def index
    @workouts = Workout.all
  end

  def show
    @workout = User.find(params[:workout_id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      session[:workout_id] = @workout.id
      redirect_to user_profile_path(current_user),
      notice: "Thank you for posting your workout #{@user.first_name.titlecase}"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def workout_params
    params.require(:workout).permit(
                              :date, :workout,
      :motivation_level, :length_lifting, :length_hitting_cardio
    )
  end


end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout, html: {class: 'form-horizontal', role: "form"}) do |f| %>
  <% if @workout.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this workout from being saved:</h4>

      <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :date, class: "col-sm-2 control-label" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :workout, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :workout, class: "col-sm-2 control-label" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :motivation_level, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :motivation_level, class: "col-sm-2 control-label" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :length_lifting, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :length_lifting, class: "col-sm-2 control-label" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :length_hitting_cardio, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :length_hitting_cardio, class: "col-sm-2 control-label" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Post Workout', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/workouts/index.html.erb
<h1 align="center">Workouts Index</h1>

<%# for the dropdown to be centered %>
<body align="center"></body>

app/views/workouts/new.html.erb
<div class="page-header">
  <%= link_to root_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Workout</h1>
</div>


<%= render 'form' %>

app/views/workouts/show.html.erb
<div class="page-header">
  <%= link_to workouts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%# link_to edit_workout_path(@workout), class: 'btn btn-primary' do %>
   <%# <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Workout</h1>
</div>

<dl class="dl-horizontal">
  <dt>Date workout was complete:</dt>
  <dd><%= @workout.date %></dd>

  <dt>Workout Hit:</dt>
  <dd><%= @workout.workout %></dd>

  <dt>The workouts motivation level:</dt>
  <dd><%= @workout.motivation_level %></dd>

  <dt>Time spent lifting:</dt>
  <dd><%= @workout.length_lifting %></dd>

  <dt>Time spent doing cardio</dt>
  <dd><%= @workout.length_hitting_cardio %></dd>
</dl>