config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  resources :comments
  resources :posts
  get 'recipes/index'

  get 'nutrition_news/index'

  get 'news/index'

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :workoutposts
  root 'main#index'

  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }


  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete '/logout',
    to: 'sessions#destroy'

  get 'users/:id' => 'users#show', :as => 'user_profile'

  get 'about' => 'main#about'
  get 'contact' => 'main#contact'


  get 'workouts/new' => 'workouts#new'
  get 'workouts' => 'workouts#index'
  get 'workouts/show/:workouts_id' => 'workouts#show', :as => 'show_workout'

  get 'new' => 'news#index'

  get 'video' => 'video#index'

  get 'chest' => 'main#chest'
  get 'arms' => 'main#arms'
  get 'back' => 'main#back'
  get 'cardio' => 'main#cardio'
  get 'legs' => 'main#legs'


  get '/auth/:provider/callback', to: 'sessions#oauth'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
end

app/models/recipe.rb
class Recipe
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)
  has_many :posts, dependent: :destroy

  validates_confirmation_of :password, if: ->(user) { !user.omniauth? && user.password.present? }
  validates_presence_of :password, on: :create, if: ->(user) { !user.omniauth? }
  validates_presence_of :password_confirmation, if: ->(user) { !user.omniauth? && user.password.present?}
end

app/models/workout.rb
class Workout < ActiveRecord::Base
end

app/models/workoutpost.rb
class Workoutpost < ActiveRecord::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @results = Google::Search::News.new(query: 'fitness')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :motivation_level, :how_long, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:id] = @user.id
      redirect_to user_profile_path(current_user),
        notice: "Thank you for signing up #{@user.first_name.titlecase}"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end

  private

  def user_params
    params.require(:user).permit(
      :username, :first_name, :last_name,
      :email, :password, :password_confirmation, :omniauth
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/nutrition_news_helper.rb
module NutritionNewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/workoutposts_helper.rb
module WorkoutpostsHelper
  def sortable(column, title=nil)
    title ||= column.titleize
    direction = direction_for_column(column)
    link_to title, sort: column, direction: direction
  end


  private

  def direction_for_column(column)
    (column == params[:sort] && params[:direction] == 'asc') ? 'desc' : 'asc'
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_authentication.html.erb
<div class="page-header"></div>
<% if current_user %>
  Signed in as <%= current_user.email%>
  <br>
  <%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
  <br>
  <%= link_to 'Signup', new_user_path %>
  <br>
  <%= link_to 'Login', login_path %>
<% end %>
<body align="center"></body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "#{current_user.first_name}", user_profile_path(current_user), class: "navbar-dropdown navbar-brand" %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete, class: 'glyphicon glyphicon-log-out' %></li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/users/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
        <% end %>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/contact">Contact</a></li>
          <li><a href="/workoutposts">All Workouts</a></li>
          <li><a href="/news/index">Fitness News</a></li>
          <li><a href="/nutrition_news/index">Nutrition News</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <div class="container">

    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>